name: Build Shattered PD iOS IPA
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew

      - name: Build Unsigned IPA via RoboVM
        run: ./gradlew :ios:createIpa

      - name: Upload Finished IPA
        uses: actions/upload-artifact@v4
        with:
          name: shattered-pd-ipa
          path: ios/build/robovm/*.ipa
